services:

  app:
    container_name: ${SERVICE_NAME}-app
    image: ghcr.io/julienpillaud/julienpillaud:${IMAGE_TAG}
    restart: always
    networks:
      - proxy
      - internal
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8000
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${HOST}`)
      - traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure
      - traefik.http.routers.${SERVICE_NAME}.tls=true

  redis:
    container_name: redis
    image: redis:8.4
    restart: always
    networks:
      - internal

  gotenberg:
    container_name: gotenberg
    image: gotenberg/gotenberg:8
    restart: always
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
    driver: bridge
