from typing import Protocol

from app.domain.admin.entities import RefreshToken, RefreshTokenExternal, User
from app.domain.entities import EntityId
from app.domain.resume.entities import Experience, Metadata
from app.domain.skills.entities import Skill, SkillCategory


class RepositoryProtocol(Protocol):
    # refresh_tokens
    async def save_token(self, value: RefreshTokenExternal, /) -> None: ...

    async def get_token_by_hash(self, value: str, /) -> RefreshToken | None: ...

    async def revoke_token(self, token_id: EntityId) -> None: ...

    async def revoke_all_tokens_for_user(self, user_id: EntityId) -> None: ...

    # users
    async def get_user(self, user_id: EntityId) -> User | None: ...

    async def get_user_by_username(self, username: str) -> User | None: ...

    # metadata
    async def get_metadata(self) -> Metadata: ...

    # experiences
    async def get_experiences(self) -> list[Experience]: ...

    # skills
    async def get_skills(self) -> list[Skill]: ...

    async def get_skill(self, skill_id: EntityId) -> Skill | None: ...

    async def create_skill(self, entity: Skill, /) -> Skill: ...

    async def update_skill(self, entity: Skill, /) -> Skill: ...

    async def delete_skill(self, entity: Skill, /) -> None: ...

    async def delete_skills_by_category(self, category_id: EntityId) -> None: ...

    async def get_category_by_id(
        self,
        category_id: EntityId,
    ) -> SkillCategory | None: ...
