from typing import Protocol

from app.domain.admin.entities import RefreshToken, RefreshTokenExternal, User
from app.domain.entities import EntityId
from app.domain.resume.entities import Experience, Metadata, Skill


class RepositoryProtocol(Protocol):
    async def save_token(self, value: RefreshTokenExternal, /) -> None: ...

    async def get_token_by_hash(self, value: str, /) -> RefreshToken | None: ...

    async def revoke_token(self, token_id: EntityId) -> None: ...

    async def revoke_all_tokens_for_user(self, user_id: EntityId) -> None: ...

    async def get_user(self, user_id: EntityId) -> User | None: ...

    async def get_user_by_username(self, username: str) -> User | None: ...

    async def get_metadata(self) -> Metadata: ...

    async def get_experiences(self) -> list[Experience]: ...

    async def get_skills(self) -> list[Skill]: ...
