name: 🧹 Lint - Frontend

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6  # v2.2.0

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun run lint

      - name: Run format
        run: bun run format

      - name: Run type checking
        run: bun run type-check
